# Background and foreground colors
background = #06040b
foreground = #ded7e8

# Standard colors
palette = 0=#090611
palette = 1=#e06ba8
palette = 2=#a99acb
palette = 3=#d9c979
palette = 4=#9563da
palette = 5=#a746e8
palette = 6=#bd9eea
palette = 7=#ded7e8

# Bright colors
palette = 8=#342346
palette = 9=#e06ba8
palette = 10=#a99acb
palette = 11=#d9c979
palette = 12=#9563da
palette = 13=#a746e8
palette = 14=#bd9eea
palette = 15=#ffffff
