$color = rgba(9, 6, 17, 1)
$inner_color = rgba(9, 6, 17, 0.70)
$outer_color = rgba(167, 70, 232, 1)
$font_color = rgba(222, 215, 232, 1)
$placeholder_color = rgba(222, 215, 232, 0.7)
$check_color = rgba(189, 158, 234, 1)
